apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-deployment
spec:
  selector:
    matchLabels:
      app: wil
  replicas: 4
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
      - name: wil
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-service
spec:
  type: ClusterIP
  selector:
    app: wil
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
