apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-deployment
spec:
  selector:
    matchLabels:
      app: wil
  replicas: 2
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
      - name: wil
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-service
spec:
  selector:
    app: wil
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
